
const products = [
  {
    id: 1,
    name: "Women's Desk-to-Dinner Cotton Stretch Formal Shirt",
    slug: "womens-cotton-stretch-formal-shirt",
    description:
      "Smart cuffs on the sleeves, button down, stylish office wear.",
    discount: 30,
    price: 99.99,
    listPrice: 139.99,
    images: [
      "https://m.media-amazon.com/images/I/61eZiSLbBpL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71rbrJS2RjL._SX522_.jpg",
    ],
    gender: "Women",
    category: "Shirts",
    brand: "Shrink",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    color: ["Blue", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 2,
    name: "Men's Slim Fit Jeans",
    slug: "mens-slim-fit-jeans",
    description: "Comfortable slim fit denim jeans for everyday wear.",
    discount: 20,
    price: 1299.99,
    listPrice: 1599.99,
    images: [
      "https://images.unsplash.com/photo-1510867759970-3d2ca293be77?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1644209114272-012e5c0b8041?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Jeans",
    brand: "Levi's",
    tags: ["best-seller", "casual"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 120,
    numSales: 500,
    countInStock: 35,
    color: ["Blue", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 3,
    name: "Red Sneakers",
    slug: "red-sneakers",
    description: "Trendy sneakers with cushioned sole.",
    discount: 25,
    price: 1999.0,
    listPrice: 2499.0,
    images: [
      "https://images.unsplash.com/photo-1710553455489-0cda9a34f0bb?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1710553455483-b8c48d365c23?w=500&auto=format&fit=crop",
    ],
    gender: "Unisex",
    category: "Footwear",
    brand: "Nike",
    tags: ["today-deal", "sports"],
    isPublished: true,
    avgRating: 4.0,
    numReviews: 200,
    numSales: 800,
    countInStock: 20,
    color: ["Red", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 4,
    name: "Leather Backpack",
    slug: "leather-backpack",
    description: "Stylish leather backpack for women.",
    discount: 15,
    price: 2499.0,
    listPrice: 2899.0,
    images: [
      "https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600",
      "https://images.unsplash.com/photo-1600180758890-6b94519a3c1f?w=600",
    ],
    gender: "Women",
    category: "Bags",
    brand: "Fossil",
    tags: ["new-arrival", "bags"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 60,
    numSales: 150,
    countInStock: 15,
    color: ["Brown", "Black"],
    sizes: ["Standard"],
    reviews: [],
  },
  {
    id: 5,
    name: "Smart Wrist Watch",
    slug: "smart-wrist-watch",
    description: "Digital smart watch with fitness tracking.",
    discount: 10,
    price: 3499.0,
    listPrice: 3999.0,
    images: [
      "https://images.unsplash.com/photo-1620625515032-6ed0c1790c75?q=80&w=464&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=500&auto=format&fit=crop",
    ],
    gender: "Unisex",
    category: "Accessories",
    brand: "Fossil",
    tags: ["best-seller", "today-deal"],
    isPublished: true,
    avgRating: 4.8,
    numReviews: 85,
    numSales: 300,
    countInStock: 50,
    color: ["Black", "Silver"],
    sizes: ["Standard"],
    reviews: [],
  },
  {
    id: 6,
    name: "Orange Summer Top",
    slug: "orange-summer-top",
    description: "Lightweight cotton top for summer.",
    discount: 6,
    price: 799.0,
    listPrice: 799.0,
    images: [
      "https://images.unsplash.com/photo-1762343950498-e28f15873035?q=80&w=870&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1762343937033-b9a3f9fc635b?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Tops",
    brand: "Zara",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 40,
    numSales: 120,
    countInStock: 25,
    color: ["Orange"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 7,
    name: "Black Graphic T-Shirt",
    slug: "black-graphic-tshirt",
    description: "Casual cotton t-shirt with graphic print.",
    discount: 5,
    price: 699.0,
    listPrice: 749.0,
    images: [
      "https://images.unsplash.com/photo-1666358777085-099cb64f2136?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1666358777336-df0ec48f5db1?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "H&M",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 3.9,
    numReviews: 70,
    numSales: 200,
    countInStock: 40,
    color: ["Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 8,
    name: "Stylish Boots",
    slug: "stylish-boots",
    description: "Durable leather boots for winter.",
    discount: 20,
    price: 2799.0,
    listPrice: 3499.0,
    images: [
      "https://plus.unsplash.com/premium_photo-1729104895462-a5fb819542b1?q=80&w=870&auto=format&fit=crop",
      "https://plus.unsplash.com/premium_photo-1729104895426-24d9a3cecc97?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "Puma",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 90,
    numSales: 250,
    countInStock: 30,
    color: ["Brown", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 10,
    name: "Casual Hoodie",
    slug: "casual-hoodie",
    description: "Warm cotton hoodie for casual wear and winter comfort.",
    discount: 15,
    price: 1499.0,
    listPrice: 1799.0,
    images: [
      "https://images.unsplash.com/photo-1646142444991-6896b6a3b6e7?q=80&w=464&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1646142445048-a6ce5580d21f?q=80&w=464&auto=format&fit=crop",
    ],
    gender: "Unisex",
    category: "Hoodies",
    brand: "Adidas",
    tags: ["new-arrival", "best-seller"],
    isPublished: true,
    avgRating: 4.4,
    numReviews: 110,
    numSales: 400,
    countInStock: 45,
    color: ["Grey", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [
      { user: "Rahul", rating: 5, comment: "Very comfortable and stylish." },
      { user: "Sneha", rating: 4, comment: "Good quality, keeps warm." },
    ],
  },

  {
    id: 11,
    name: "Formal Blazer",
    slug: "formal-blazer",
    description: "Classic slim fit blazer for office wear.",
    discount: 20,
    price: 3499.0,
    listPrice: 3999.0,
    images: [
      "https://plus.unsplash.com/premium_photo-1661455889538-5a67360cdb11?q=80&w=387&auto=format&fit=crop",
      "https://plus.unsplash.com/premium_photo-1661455894928-45a49794eb7b?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Blazers",
    brand: "Arrow",
    tags: ["best-seller", "formal"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 95,
    numSales: 250,
    countInStock: 20,
    color: ["Black", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 12,
    name: "Women's Maxi Dress",
    slug: "womens-maxi-dress",
    description: "Elegant maxi dress for parties and events.",
    discount: 25,
    price: 2299.0,
    listPrice: 2999.0,
    images: [
      "https://images.unsplash.com/photo-1741816219281-371d26f23fb7?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1741816219785-a642b0ad30b8?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Dresses",
    brand: "Zara",
    tags: ["new-arrival", "fashion"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 70,
    numSales: 180,
    countInStock: 25,
    color: ["Red", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 13,
    name: "Sports Tracksuit",
    slug: "sports-tracksuit",
    description: "Comfortable tracksuit for gym and sports.",
    discount: 30,
    price: 1999.0,
    listPrice: 2499.0,
    images: [
      "https://images.unsplash.com/photo-1602670935585-db18a44de499?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1602670935908-094f41dcb67c?w=500&auto=format&fit=crop",
    ],
    gender: "Unisex",
    category: "Sportswear",
    brand: "Nike",
    tags: ["today-deal", "sports"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 150,
    numSales: 600,
    countInStock: 40,
    color: ["Black", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 14,
    name: "Women's Handbag",
    slug: "womens-handbag",
    description: "Stylish handbag with spacious compartments.",
    discount: 10,
    price: 1799.0,
    listPrice: 1999.0,
    images: [
      "https://images.unsplash.com/photo-1691480250099-a63081ecfcb8?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1691480150204-66dd1eb77391?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Bags",
    brand: "Fossil",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 80,
    numSales: 220,
    countInStock: 30,
    color: ["Brown", "Black"],
    sizes: ["Standard"],
    reviews: [],
  },
  {
    id: 15,
    name: "Casual Polo T-Shirt",
    slug: "casual-polo-tshirt",
    description: "Cotton polo t-shirt for casual wear.",
    discount: 5,
    price: 599.0,
    listPrice: 649.0,
    images: [
      "https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?q=80&w=387&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1622383128901-aa2c3399c75c?q=80&w=387&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Puma",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 3.8,
    numReviews: 50,
    numSales: 140,
    countInStock: 60,
    color: ["White", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 16,
    name: "Women's Heels",
    slug: "womens-heels",
    description: "Elegant heels for parties and events.",
    discount: 20,
    price: 2499.0,
    listPrice: 2999.0,
    images: [
      "https://images.unsplash.com/photo-1596702876489-9d11e5806161?q=80&w=435&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596702874230-b5706dfb5bc7?q=80&w=435&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "Zara",
    tags: ["new-arrival", "fashion"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 65,
    numSales: 170,
    countInStock: 20,
    color: ["Red", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 17,
    name: "Men's Leather Belt",
    slug: "mens-leather-belt",
    description: "Durable leather belt for formal wear.",
    discount: 15,
    price: 799.0,
    listPrice: 999.0,
    images: [
      "https://images.unsplash.com/photo-1684510334550-0c4fa8aaffd1?q=80&w=870&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1664286074240-d7059e004dff?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "Arrow",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 90,
    numSales: 300,
    countInStock: 50,
    color: ["Brown", "Black"],
    sizes: ["Standard"],
    reviews: [],
  },
  {
    id: 18,
    name: "Women's Kurti",
    slug: "womens-kurti",
    description: "Traditional cotton kurti for daily wear.",
    discount: 10,
    price: 999.0,
    listPrice: 1199.0,
    images: [
      "https://images.unsplash.com/photo-1669194722832-1b708623457c?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1669194721813-b9fc575cee97?q=80&w=435&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Ethnic Wear",
    brand: "FabIndia",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 75,
    numSales: 210,
    countInStock: 40,
    color: ["Pink", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 19,
    name: "Men's Sports Jacket",
    slug: "mens-sports-jacket",
    description:
      "Lightweight sports jacket suitable for outdoor activities and casual wear.",
    discount: 20,
    price: 2499.0,
    listPrice: 2999.0,
    images: [
      "https://images.unsplash.com/photo-1757937603996-c8dbcb9e248c?q=80&w=387&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1762025892133-29d96f24b321?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Jackets",
    brand: "Nike",
    tags: ["today-deal", "sports"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 95,
    numSales: 320,
    countInStock: 25,
    color: ["Black", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 20,
    name: "Men's Running Shoes",
    slug: "mens-running-shoes",
    description: "Lightweight running shoes with cushioned sole.",
    discount: 25,
    price: 2199.0,
    listPrice: 2799.0,
    images: [
      "https://images.unsplash.com/photo-1709258228137-19a8c193be39?q=80&w=511&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1709258228137-19a8c193be39?q=80&w=511&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Adidas",
    tags: ["best-seller", "sports"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 180,
    numSales: 600,
    countInStock: 40,
    color: ["Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 21,
    name: "Women's Summer Dress",
    slug: "womens-summer-dress",
    description: "Light cotton dress perfect for summer outings.",
    discount: 15,
    price: 1499.0,
    listPrice: 1799.0,
    images: [
      "https://images.unsplash.com/photo-1630540666475-c40d69ee29b6?q=80&w=413&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1630544309715-5f416a525b8b?q=80&w=387&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Dresses",
    brand: "Zara",
    tags: ["new-arrival", "fashion"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 90,
    numSales: 250,
    countInStock: 30,
    color: ["Yellow", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 22,
    name: "Men's Formal Shoes",
    slug: "mens-formal-shoes",
    description: "Classic leather shoes for office wear.",
    discount: 20,
    price: 2599.0,
    listPrice: 3199.0,
    images: [
      "https://images.unsplash.com/photo-1563434564528-8fdf5996e622?q=80&w=870&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1563434649554-58f91d22ec2c?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Red Chief",
    tags: ["best-seller", "formal"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 120,
    numSales: 400,
    countInStock: 25,
    color: ["Brown", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 23,
    name: "Women's Handcrafted Kurti",
    slug: "womens-handcrafted-kurti",
    description: "Traditional handcrafted kurti with embroidery.",
    discount: 10,
    price: 1299.0,
    listPrice: 1499.0,
    images: [
      "https://images.unsplash.com/photo-1650603696323-9002b8fb7716?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1650603697724-6492ae0e2e63?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Ethnic Wear",
    brand: "FabIndia",
    tags: ["new-arrival", "ethnic"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 75,
    numSales: 200,
    countInStock: 35,
    color: ["Pink", "Green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 24,
    name: "Men's Casual Shirt",
    slug: "mens-casual-shirt",
    description: "Cotton casual shirt for everyday wear.",
    discount: 5,
    price: 899.0,
    listPrice: 999.0,
    images: [
      "https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?q=80&w=464&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1624835589323-442670703bc0?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Arrow",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.0,
    numReviews: 60,
    numSales: 150,
    countInStock: 50,
    color: ["Blue", "White"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 25,
    name: "Women's Sandals",
    slug: "womens-sandals",
    description: "Comfortable sandals for daily wear.",
    discount: 20,
    price: 999.0,
    listPrice: 1299.0,
    images: [
      "https://images.unsplash.com/photo-1564051806-be616e3bdcec?q=80&w=464&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1564051806-be616e3bdcec?q=80&w=464&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "Bata",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 80,
    numSales: 220,
    countInStock: 40,
    color: ["Brown", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 26,
    name: "Men's Hoodie Jacket",
    slug: "mens-hoodie-jacket",
    description: "Warm hoodie jacket for winter.",
    discount: 15,
    price: 1799.0,
    listPrice: 2099.0,
    images: [
      "https://images.unsplash.com/photo-1701673072655-0b7c89ec2138?q=80&w=387&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1701673072655-0b7c89ec2138?q=80&w=387&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Hoodies",
    brand: "Puma",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 95,
    numSales: 280,
    countInStock: 30,
    color: ["Grey", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 27,
    name: "Women's Party Gown",
    slug: "womens-party-gown",
    description: "Elegant gown for parties and weddings.",
    discount: 30,
    price: 3999.0,
    listPrice: 4999.0,
    images: [
      "https://images.unsplash.com/photo-1765229279946-f265fa703385?q=80&w=387&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1765229279946-f265fa703385?q=80&w=387&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Dresses",
    brand: "Zara",
    tags: ["best-seller", "fashion"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 120,
    numSales: 350,
    countInStock: 20,
    color: ["Red", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 28,
    name: "Men's Sports Shorts",
    slug: "mens-sports-shorts",
    description:
      "Breathable polyester shorts designed for gym, running, and sports activities.",
    discount: 10,
    price: 699.0,
    listPrice: 799.0,
    images: [
      "https://images.unsplash.com/photo-1695918428860-a3bc6a2f1d4b?q=80&w=870&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1695918428860-a3bc6a2f1d4b?q=80&w=870&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Sportswear",
    brand: "Nike",
    tags: ["today-deal", "sports"],
    isPublished: true,
    avgRating: 4.0,
    numReviews: 70,
    numSales: 200,
    countInStock: 60,
    color: ["Black", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [
      {
        user: "Ravi",
        rating: 4,
        comment: "Comfortable and lightweight for workouts.",
      },
      {
        user: "Neha",
        rating: 5,
        comment: "Perfect fit, fabric quality is great.",
      },
    ],
  },
  {
    id: 29,
    name: "Women's Casual Sneakers",
    slug: "womens-casual-sneakers",
    description:
      "Comfortable casual sneakers designed for everyday wear and light outdoor activities.",
    discount: 20,
    price: 1599.0,
    listPrice: 1999.0,
    images: [
      "https://plus.unsplash.com/premium_photo-1723615218251-91af00a20c0a?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1720171116445-ee61d606c7bc?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "Puma",
    tags: ["new-arrival", "today-deal"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 85,
    numSales: 260,
    countInStock: 35,
    color: ["White", "Pink"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [
      {
        user: "Anjali",
        rating: 5,
        comment: "Very stylish and comfortable for daily use.",
      },
      {
        user: "Ravi",
        rating: 4,
        comment: "Good quality, but size runs slightly small.",
      },
    ],
  },

  {
    id: 30,
    name: "Women's Floral Skirt",
    slug: "womens-floral-skirt",
    description:
      "Lightweight cotton skirt with floral print, ideal for summer wear.",
    discount: 20,
    price: 1299.0,
    listPrice: 1599.0,
    images: [
      "https://images.unsplash.com/photo-1603290939650-b553549a5739?q=80&w=387&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1603290939650-b553549a5739?q=80&w=387&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Skirts",
    brand: "Zara",
    tags: ["new-arrival", "fashion"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 85,
    numSales: 220,
    countInStock: 30,
    color: ["Pink", "Yellow"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 31,
    name: "Unisex Sports Cap",
    slug: "unisex-sports-cap",
    description:
      "Adjustable sports cap with breathable fabric, perfect for outdoor activities.",
    discount: 10,
    price: 499.0,
    listPrice: 599.0,
    images: [
      "https://images.unsplash.com/photo-1618338110322-7d3f30a479cc?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1539850310365-b99c16f4b992?w=500&auto=format&fit=crop",
    ],
    gender: "Unisex",
    category: "Accessories",
    brand: "Nike",
    tags: ["today-deal", "sports"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 60,
    numSales: 180,
    countInStock: 50,
    color: ["Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 32,
    name: "Men's Leather Wallet",
    slug: "mens-leather-wallet",
    description:
      "Premium leather wallet with multiple card slots and coin pocket.",
    discount: 5,
    price: 799.0,
    listPrice: 899.0,
    images: [
      "https://images.unsplash.com/photo-1576616074021-f6b73bbabde4?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614330315526-166f2d71e544?q=80&w=388&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "Arrow",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 90,
    numSales: 300,
    countInStock: 70,
    color: ["Brown", "Black"],
    sizes: ["Standard"],
    reviews: [],
  },
  {
    id: 33,
    name: "Women's Winter Coat",
    slug: "womens-winter-coat",
    description:
      "Warm woolen coat with stylish design, perfect for winter season.",
    discount: 25,
    price: 3499.0,
    listPrice: 4599.0,
    images: [
      "https://images.unsplash.com/photo-1552256028-c51f32398295?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552256028-71eb9a7ff27d?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Coats",
    brand: "H&M",
    tags: ["new-arrival", "fashion"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 110,
    numSales: 280,
    countInStock: 25,
    color: ["Grey", "Black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 34,
    name: "Men's Casual Sneakers",
    slug: "mens-casual-sneakers",
    description:
      "Lightweight sneakers with breathable mesh, perfect for casual wear and walking.",
    discount: 15,
    price: 1799.0,
    listPrice: 2099.0,
    images: [
      "https://images.unsplash.com/photo-1613456680024-b590975f78be?q=80&w=870&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1696980488636-0cf971ba63a9?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Adidas",
    tags: ["best-seller", "today-deal"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 95,
    numSales: 280,
    countInStock: 35,
    color: ["Black", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 35,
    name: "Women's Silk Saree",
    slug: "womens-silk-saree",
    description:
      "Elegant silk saree with golden border, perfect for festive occasions.",
    discount: 25,
    price: 3499.0,
    listPrice: 4599.0,
    images: [
      "https://images.unsplash.com/photo-1597897545901-6ac15b725974?q=80&w=387&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1597897544945-e9f0a3e6f962?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Ethnic Wear",
    brand: "FabIndia",
    tags: ["new-arrival", "fashion"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 120,
    numSales: 350,
    countInStock: 20,
    color: ["Red", "Gold"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 36,
    name: "Unisex Smartwatch",
    slug: "unisex-smartwatch",
    description:
      "Digital smartwatch with fitness tracking, heart rate monitor, and notifications.",
    discount: 10,
    price: 2999.0,
    listPrice: 3499.0,
    images: [
      "https://images.unsplash.com/photo-1542541864-4abf21a55761?q=80&w=403&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1648280706575-24c900233c6d?w=500&auto=format&fit=crop",
    ],
    gender: "Unisex",
    category: "Accessories",
    brand: "Fossil",
    tags: ["best-seller", "today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 150,
    numSales: 500,
    countInStock: 40,
    color: ["Black", "Silver"],
    sizes: ["Standard"],
    reviews: [],
  },
  {
    id: 37,
    name: "Men's Formal Shirt",
    slug: "mens-formal-shirt",
    description:
      "Slim fit cotton shirt, ideal for office and formal occasions.",
    discount: 20,
    price: 1199.0,
    listPrice: 1499.0,
    images: [
      "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1656453260437-4f4da3ef81dc?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Arrow",
    tags: ["new-arrival", "formal"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 80,
    numSales: 220,
    countInStock: 50,
    color: ["White", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },

  {
    id: 38,
    name: "Women's Cotton Kurti",
    slug: "womens-cotton-kurti",
    description:
      "Comfortable cotton kurti with printed design, ideal for daily wear.",
    discount: 15,
    price: 999.0,
    listPrice: 1199.0,
    images: [
      "https://images.unsplash.com/photo-1693987026907-c00c974ddcda?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1693987071149-2054859f159a?w=500&auto=format&fit=crop",
    ],
    gender: "Women",
    category: "Ethnic Wear",
    brand: "FabIndia",
    tags: ["new-arrival", "ethnic"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 80,
    numSales: 200,
    countInStock: 40,
    color: ["Blue", "Green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 39,
    name: "Unisex Backpack",
    slug: "unisex-backpack",
    description:
      "Durable backpack with multiple compartments, suitable for travel and college.",
    discount: 10,
    price: 1499.0,
    listPrice: 1699.0,
    images: [
      "https://images.unsplash.com/photo-1719150814182-f54287c937e7?w=500&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1719150811630-a8edde33ecd4?w=500&auto=format&fit=crop",
    ],
    gender: "Unisex",
    category: "Bags",
    brand: "Wildcraft",
    tags: ["best-seller", "today-deal"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 95,
    numSales: 300,
    countInStock: 50,
    color: ["Black", "Grey"],
    sizes: ["Standard"],
    reviews: [],
  },
  {
    id: 40,
    name: "Men's Polo T-Shirt",
    slug: "mens-polo-tshirt",
    description:
      "Classic cotton polo t-shirt with collar, perfect for casual wear.",
    discount: 5,
    price: 799.0,
    listPrice: 899.0,
    images: [
      "https://images.unsplash.com/photo-1652695904797-36512b95c45a?q=80&w=387&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1652695904846-37cc9462a700?w=500&auto=format&fit=crop",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Arrow",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.0,
    numReviews: 70,
    numSales: 180,
    countInStock: 60,
    color: ["White", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
];
